[package]
name = "spotify-adblock"
version = "1.0.2"
authors = ["abba23"]
description = "Adblocker for Spotify"
edition = "2018"

[dependencies]
lazy_static = "*"
libc = "*"
regex = ">=1.5.5"
serde = { version = "*", features = ["derive"] }
toml = "*"

[lib]
name = "spotifyadblock"
crate_type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3
panic = "abort"
